Repository betagouv/aplus, pull requests merged in 2019-11, with the labels that each got.

#258 Update javax.mail to 1.6.2
  build.sbt
Labels: dependency

#259 Update play-ahc-ws, play-guice, play-jdbc, ... to 2.6.24
  project/plugins.sbt
Labels: dependency

#262 Update sentry-logback to 1.7.28
  build.sbt
Labels: dependency

#260 Update play-json-joda to 2.6.14
  build.sbt
Labels: dependency

#261 Update play-mailer, play-mailer-guice to 7.0.1
  build.sbt
Labels: dependency

#264 Update anorm to 2.6.5
  build.sbt
Labels: dependency

#267 Update sbt-scoverage to 1.6.0
  project/plugins.sbt
Labels: dependency

#268 Update chartjs to 2.7.3
  build.sbt
Labels: dependency

#270 Update dialog-polyfill to 0.4.10
  build.sbt
Labels: dependency

#271 Update roboto-fontface to 0.10.0
  build.sbt
Labels: dependency

#265 Update postgresql to 42.2.8
  build.sbt
Labels: dependency

#266 Update sbt to 1.3.3
  project/build.properties
Labels: dependency

#289 [209] Si une personne appuis sur le bouton de connexion en même temps que la redirection, il peut se retrouver déconnecté
  app/views/loginHome.scala.html
Labels: bug

#296 Fix : rétablissement des notifications pour les personnes invités dans la demande
  app/services/NotificationService.scala
Labels: bug

#253 [191] Proposition de design + Nouveau Logo
  app/constants/Constants.scala
  app/controllers/ApplicationController.scala
  app/views/CSVExport.scala.html
  app/views/allApplications.scala.html
  app/views/allEvents.scala.html
  app/views/allUsers.scala.html
  app/views/createApplication.scala.html
  app/views/editGroup.scala.html
  app/views/editUser.scala.html
  app/views/editUsers.scala.html
  app/views/emails/notificationBAL.scala.html
  app/views/help.scala.html
  app/views/helpers/usersInformations.scala.html
  app/views/loginHome.scala.html
  app/views/main.scala.html
  app/views/myApplications.scala.html
  app/views/showApplication.scala.html
  app/views/showCGU.scala.html
  app/views/simplifiedCreateApplication.scala.html
  app/views/stats.scala.html
  build.sbt
  conf/routes
  public/html/CGU_13_mai_2019.html
  public/images/logo_120.png
  public/images/logo_422.png
  public/images/logo_full_500x397.png
  public/images/logo_small_150x160.png
  public/stylesheets/main.css
  public/stylesheets/newForm.css
Labels: enhancement

#224 [106] Formulaire d'importation d'utilisateurs (WIP)
  app/controllers/UserController.scala
  app/csv/GroupImport.scala
  app/csv/UserImport.scala
  app/csv/package.scala
  app/extentions/Operators.scala
  app/models/Area.scala
  app/models/Organisation.scala
  app/models/User.scala
  app/models/UserGroup.scala
  app/services/UserGroupService.scala
  app/views/allUsers.scala.html
  app/views/importUsers.scala.html
  app/views/reviewUsersImport.scala.html
  build.sbt
  conf/routes
  public/stylesheets/main.css
  test/csv/CSVSpec.scala
Labels: enhancement
